---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloudComputing-eksctl-demo
  region: us-east-2

managedNodeGroups:
- name: nodegroup
  instanceType: t2.micro
  desiredCapacity: 3
  ssh:
          allow: false