apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcomputing-deployment
  labels:
    app: spacexdemo_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacexdemo_app
  template:
    metadata:
      labels:
        app: spacexdemo_app
    spec:
      containers:
      - name: spacexdemo-app
        image: 618684570199.dkr.ecr.us-east-2.amazonaws.com/spacexdemo_app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: spacexdemo-app-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer 
  selector:
    app: spacexdemo_app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000